/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DropDown {
        "align": string;
    }
    interface FieldButton {
        "disabled": boolean;
        "kind": string;
        "size": string;
        "spinner": boolean;
        "theme": string;
        /**
          * PROPS
         */
        "type": string;
    }
    interface FieldCheckbox {
        /**
          * PROPS
         */
        "autofocus": boolean;
        "autowidth": boolean;
        "disabled": boolean;
        "error": string;
        "getValidationMessage": () => Promise<string>;
        /**
          * METHODS
         */
        "getValidity": () => Promise<ValidityState>;
        "helptext": string;
        "inputid": string;
        "label": string;
        "mixed": boolean;
        "name": string;
        "readonly": boolean;
        "required": boolean;
        "slim": boolean;
        "value": boolean;
    }
    interface FieldMultiselect {
        /**
          * PROPS
         */
        "autofocus": boolean;
        "autowidth": boolean;
        "disabled": boolean;
        "error": string;
        "getValidationMessage": () => Promise<string>;
        /**
          * METHODS
         */
        "getValidity": () => Promise<ValidityState>;
        "helptext": string;
        "label": string;
        "name": string;
        "options": string | any[];
        "readonly": boolean;
        "required": boolean;
        "slim": boolean;
        "value": any[];
    }
    interface FieldNumber {
        /**
          * PROPS
         */
        "autocomplete": string;
        "autofocus": boolean;
        "autowidth": boolean;
        "disabled": boolean;
        "error": string;
        "getValidationMessage": () => Promise<string>;
        /**
          * METHODS
         */
        "getValidity": () => Promise<ValidityState>;
        "helptext": string;
        "iconalign": string;
        "inputid": string;
        "label": string;
        "labelalign": string;
        "max": number;
        "min": number;
        "name": string;
        "readonly": boolean;
        "required": boolean;
        "slim": boolean;
        "value": number | undefined;
    }
    interface FieldRadio {
        /**
          * PROPS
         */
        "autowidth": boolean;
        "disabled": boolean;
        "error": string;
        "getValidationMessage": () => Promise<string>;
        /**
          * METHODS
         */
        "getValidity": () => Promise<ValidityState>;
        "helptext": string;
        "inputid": string;
        "label": string;
        "name": string;
        "options": string | any[];
        "readonly": boolean;
        "required": boolean;
        "slim": boolean;
        "value": string | undefined;
    }
    interface FieldSelect {
        /**
          * PROPS
         */
        "autocomplete": string;
        "autowidth": boolean;
        "disabled": boolean;
        "error": string;
        "getValidationMessage": () => Promise<string>;
        /**
          * METHODS
         */
        "getValidity": () => Promise<ValidityState>;
        "helptext": string;
        "inputid": string;
        "label": string;
        "labelalign": string;
        "name": string;
        "options": string | any[];
        "required": boolean;
        "slim": boolean;
        "value": string;
    }
    interface FieldText {
        /**
          * PROPS
         */
        "autocomplete": string;
        "autofocus": boolean;
        "autowidth": boolean;
        "count": number;
        "disabled": boolean;
        "error": string;
        "getValidationMessage": () => Promise<string>;
        /**
          * METHODS
         */
        "getValidity": () => Promise<ValidityState>;
        "helptext": string;
        "inputid": string;
        "label": string;
        "labelalign": string;
        "max": number;
        "min": number;
        "name": string;
        "readonly": boolean;
        "required": boolean;
        "showcount": boolean;
        "slim": boolean;
        "type": string;
        "value": string;
    }
    interface FieldTextarea {
        /**
          * PROPS
         */
        "autocomplete": string;
        "autofocus": boolean;
        "autowidth": boolean;
        "count": number;
        "disabled": boolean;
        "error": string;
        "fullwidth": boolean;
        "getValidationMessage": () => Promise<string>;
        /**
          * METHODS
         */
        "getValidity": () => Promise<ValidityState>;
        "helptext": string;
        "inputid": string;
        "label": string;
        "labelalign": string;
        "max": number;
        "min": number;
        "name": string;
        "readonly": boolean;
        "required": boolean;
        "resize": string;
        "showcount": boolean;
        "slim": boolean;
        "value": string;
    }
    interface FieldTime {
        /**
          * PROPS
         */
        "autowidth": boolean;
        "disabled": boolean;
        "error": string;
        "getValidationMessage": () => Promise<string>;
        /**
          * METHODS
         */
        "getValidity": () => Promise<ValidityState>;
        "helptext": string;
        "hour": (value?: any) => Promise<unknown>;
        "inputid": string;
        "label": string;
        "labelalign": string;
        "max": string;
        "meridien": (value?: any) => Promise<unknown>;
        "min": string;
        "minute": (value?: any) => Promise<unknown>;
        "name": string;
        "readonly": boolean;
        "required": boolean;
        "second": (value?: any) => Promise<unknown>;
        "showseconds": boolean;
        "slim": boolean;
        "value": string;
    }
}
declare global {
    interface HTMLDropDownElement extends Components.DropDown, HTMLStencilElement {
    }
    var HTMLDropDownElement: {
        prototype: HTMLDropDownElement;
        new (): HTMLDropDownElement;
    };
    interface HTMLFieldButtonElement extends Components.FieldButton, HTMLStencilElement {
    }
    var HTMLFieldButtonElement: {
        prototype: HTMLFieldButtonElement;
        new (): HTMLFieldButtonElement;
    };
    interface HTMLFieldCheckboxElement extends Components.FieldCheckbox, HTMLStencilElement {
    }
    var HTMLFieldCheckboxElement: {
        prototype: HTMLFieldCheckboxElement;
        new (): HTMLFieldCheckboxElement;
    };
    interface HTMLFieldMultiselectElement extends Components.FieldMultiselect, HTMLStencilElement {
    }
    var HTMLFieldMultiselectElement: {
        prototype: HTMLFieldMultiselectElement;
        new (): HTMLFieldMultiselectElement;
    };
    interface HTMLFieldNumberElement extends Components.FieldNumber, HTMLStencilElement {
    }
    var HTMLFieldNumberElement: {
        prototype: HTMLFieldNumberElement;
        new (): HTMLFieldNumberElement;
    };
    interface HTMLFieldRadioElement extends Components.FieldRadio, HTMLStencilElement {
    }
    var HTMLFieldRadioElement: {
        prototype: HTMLFieldRadioElement;
        new (): HTMLFieldRadioElement;
    };
    interface HTMLFieldSelectElement extends Components.FieldSelect, HTMLStencilElement {
    }
    var HTMLFieldSelectElement: {
        prototype: HTMLFieldSelectElement;
        new (): HTMLFieldSelectElement;
    };
    interface HTMLFieldTextElement extends Components.FieldText, HTMLStencilElement {
    }
    var HTMLFieldTextElement: {
        prototype: HTMLFieldTextElement;
        new (): HTMLFieldTextElement;
    };
    interface HTMLFieldTextareaElement extends Components.FieldTextarea, HTMLStencilElement {
    }
    var HTMLFieldTextareaElement: {
        prototype: HTMLFieldTextareaElement;
        new (): HTMLFieldTextareaElement;
    };
    interface HTMLFieldTimeElement extends Components.FieldTime, HTMLStencilElement {
    }
    var HTMLFieldTimeElement: {
        prototype: HTMLFieldTimeElement;
        new (): HTMLFieldTimeElement;
    };
    interface HTMLElementTagNameMap {
        "drop-down": HTMLDropDownElement;
        "field-button": HTMLFieldButtonElement;
        "field-checkbox": HTMLFieldCheckboxElement;
        "field-multiselect": HTMLFieldMultiselectElement;
        "field-number": HTMLFieldNumberElement;
        "field-radio": HTMLFieldRadioElement;
        "field-select": HTMLFieldSelectElement;
        "field-text": HTMLFieldTextElement;
        "field-textarea": HTMLFieldTextareaElement;
        "field-time": HTMLFieldTimeElement;
    }
}
declare namespace LocalJSX {
    interface DropDown {
        "align"?: string;
    }
    interface FieldButton {
        "disabled"?: boolean;
        "kind"?: string;
        "size"?: string;
        "spinner"?: boolean;
        "theme"?: string;
        /**
          * PROPS
         */
        "type"?: string;
    }
    interface FieldCheckbox {
        /**
          * PROPS
         */
        "autofocus"?: boolean;
        "autowidth"?: boolean;
        "disabled"?: boolean;
        "error"?: string;
        "helptext"?: string;
        "inputid"?: string;
        "label"?: string;
        "mixed"?: boolean;
        "name"?: string;
        "readonly"?: boolean;
        "required"?: boolean;
        "slim"?: boolean;
        "value"?: boolean;
    }
    interface FieldMultiselect {
        /**
          * PROPS
         */
        "autofocus"?: boolean;
        "autowidth"?: boolean;
        "disabled"?: boolean;
        "error"?: string;
        "helptext"?: string;
        "label"?: string;
        "name"?: string;
        "options"?: string | any[];
        "readonly"?: boolean;
        "required"?: boolean;
        "slim"?: boolean;
        "value"?: any[];
    }
    interface FieldNumber {
        /**
          * PROPS
         */
        "autocomplete"?: string;
        "autofocus"?: boolean;
        "autowidth"?: boolean;
        "disabled"?: boolean;
        "error"?: string;
        "helptext"?: string;
        "iconalign"?: string;
        "inputid"?: string;
        "label"?: string;
        "labelalign"?: string;
        "max"?: number;
        "min"?: number;
        "name"?: string;
        "readonly"?: boolean;
        "required"?: boolean;
        "slim"?: boolean;
        "value"?: number | undefined;
    }
    interface FieldRadio {
        /**
          * PROPS
         */
        "autowidth"?: boolean;
        "disabled"?: boolean;
        "error"?: string;
        "helptext"?: string;
        "inputid"?: string;
        "label"?: string;
        "name"?: string;
        "options"?: string | any[];
        "readonly"?: boolean;
        "required"?: boolean;
        "slim"?: boolean;
        "value"?: string | undefined;
    }
    interface FieldSelect {
        /**
          * PROPS
         */
        "autocomplete"?: string;
        "autowidth"?: boolean;
        "disabled"?: boolean;
        "error"?: string;
        "helptext"?: string;
        "inputid"?: string;
        "label"?: string;
        "labelalign"?: string;
        "name"?: string;
        "options"?: string | any[];
        "required"?: boolean;
        "slim"?: boolean;
        "value"?: string;
    }
    interface FieldText {
        /**
          * PROPS
         */
        "autocomplete"?: string;
        "autofocus"?: boolean;
        "autowidth"?: boolean;
        "count"?: number;
        "disabled"?: boolean;
        "error"?: string;
        "helptext"?: string;
        "inputid"?: string;
        "label"?: string;
        "labelalign"?: string;
        "max"?: number;
        "min"?: number;
        "name"?: string;
        "readonly"?: boolean;
        "required"?: boolean;
        "showcount"?: boolean;
        "slim"?: boolean;
        "type"?: string;
        "value"?: string;
    }
    interface FieldTextarea {
        /**
          * PROPS
         */
        "autocomplete"?: string;
        "autofocus"?: boolean;
        "autowidth"?: boolean;
        "count"?: number;
        "disabled"?: boolean;
        "error"?: string;
        "fullwidth"?: boolean;
        "helptext"?: string;
        "inputid"?: string;
        "label"?: string;
        "labelalign"?: string;
        "max"?: number;
        "min"?: number;
        "name"?: string;
        "readonly"?: boolean;
        "required"?: boolean;
        "resize"?: string;
        "showcount"?: boolean;
        "slim"?: boolean;
        "value"?: string;
    }
    interface FieldTime {
        /**
          * PROPS
         */
        "autowidth"?: boolean;
        "disabled"?: boolean;
        "error"?: string;
        "helptext"?: string;
        "inputid"?: string;
        "label"?: string;
        "labelalign"?: string;
        "max"?: string;
        "min"?: string;
        "name"?: string;
        "readonly"?: boolean;
        "required"?: boolean;
        "showseconds"?: boolean;
        "slim"?: boolean;
        "value"?: string;
    }
    interface IntrinsicElements {
        "drop-down": DropDown;
        "field-button": FieldButton;
        "field-checkbox": FieldCheckbox;
        "field-multiselect": FieldMultiselect;
        "field-number": FieldNumber;
        "field-radio": FieldRadio;
        "field-select": FieldSelect;
        "field-text": FieldText;
        "field-textarea": FieldTextarea;
        "field-time": FieldTime;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "drop-down": LocalJSX.DropDown & JSXBase.HTMLAttributes<HTMLDropDownElement>;
            "field-button": LocalJSX.FieldButton & JSXBase.HTMLAttributes<HTMLFieldButtonElement>;
            "field-checkbox": LocalJSX.FieldCheckbox & JSXBase.HTMLAttributes<HTMLFieldCheckboxElement>;
            "field-multiselect": LocalJSX.FieldMultiselect & JSXBase.HTMLAttributes<HTMLFieldMultiselectElement>;
            "field-number": LocalJSX.FieldNumber & JSXBase.HTMLAttributes<HTMLFieldNumberElement>;
            "field-radio": LocalJSX.FieldRadio & JSXBase.HTMLAttributes<HTMLFieldRadioElement>;
            "field-select": LocalJSX.FieldSelect & JSXBase.HTMLAttributes<HTMLFieldSelectElement>;
            "field-text": LocalJSX.FieldText & JSXBase.HTMLAttributes<HTMLFieldTextElement>;
            "field-textarea": LocalJSX.FieldTextarea & JSXBase.HTMLAttributes<HTMLFieldTextareaElement>;
            "field-time": LocalJSX.FieldTime & JSXBase.HTMLAttributes<HTMLFieldTimeElement>;
        }
    }
}
