/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ColorResult } from "../../utils/color/color-object";
import { CurrentTransition } from "./components/element-transition/element-transition";
import { InternalValue } from "./components/field-time/field-time";
export namespace Components {
    interface AlphaSlider {
        "color": () => ColorResult;
        "value": string;
    }
    interface BackgroundFill {
        "color": string;
        "image": string;
        "line": string;
        "lineargradient": string;
        "positionx": string;
        "positiony": string;
        "radialgradient": string;
        "repeat": boolean | string;
        "sizex": string;
        "sizey": string;
    }
    interface CalendarDay {
        /**
          * PROPERTIES
         */
        "active": boolean;
        "clickable": boolean;
        "date": Date;
        /**
          * METHODS
         */
        "day": (val: any) => Promise<unknown>;
        "disabled": boolean;
        "month": (val: any) => Promise<unknown>;
        "year": (val: any) => Promise<unknown>;
    }
    interface CalendarHeader {
        /**
          * PROPS
         */
        "date": Date | string;
    }
    interface CalendarMonth {
        /**
          * PROPERTIES
         */
        "active": boolean;
        "clickable": boolean;
        "date": string | Date;
        /**
          * METHODS
         */
        "day": (val: any) => Promise<unknown>;
        "disabled": boolean;
        "month": (val: any) => Promise<unknown>;
        "year": (val: any) => Promise<unknown>;
    }
    interface ColorInputs {
        "color": () => ColorResult;
        "value": string;
    }
    interface ColorPicker {
        "color": () => ColorResult;
        "value": string;
    }
    interface ColorWheel {
        "color": () => ColorResult;
        "value": string;
    }
    interface DragX {
        "contained": boolean;
    }
    interface DragXy {
        "contained": boolean;
    }
    interface DragY {
        "contained": boolean;
    }
    interface DropDown {
        "arrow": boolean;
        "closeonclick": boolean;
        "open": boolean;
        "openonhover": boolean;
    }
    interface ElementTransition {
        "removeinactive": boolean;
        "speed": number;
        "transition": (nextElement: any) => Promise<unknown>;
    }
    interface EyeDropper {
    }
    interface FieldButton {
        "disabled": boolean;
        "kind": string;
        "nomargin": boolean;
        "size": string;
        "spinner": boolean;
        "theme": string;
        /**
          * PROPS
         */
        "type": string;
    }
    interface FieldCheckbox {
        /**
          * PROPS
         */
        "autofocus": boolean;
        "autowidth": boolean;
        "disabled": boolean;
        "error": string;
        "getValidationMessage": () => Promise<string>;
        /**
          * METHODS
         */
        "getValidity": () => Promise<ValidityState>;
        "helptext": string;
        "inputid": string;
        "label": string;
        "mixed": boolean;
        "name": string;
        "nomargin": boolean;
        "novalidate": boolean;
        "required": boolean;
        "theme": 'inverse' | '';
        "value": boolean;
    }
    interface FieldColor {
        /**
          * PROPS
         */
        "autocomplete": string;
        "autofocus": boolean;
        "autowidth": boolean;
        "disabled": boolean;
        "error": string;
        "getValidationMessage": () => Promise<string>;
        /**
          * METHODS
         */
        "getValidity": () => Promise<ValidityState>;
        "helptext": string;
        "inputid": string;
        "label": string;
        "labelup": boolean;
        "name": string;
        "nomargin": boolean;
        "required": boolean;
        "theme": 'inverse' | '';
        "value": string;
    }
    interface FieldDate {
        "active": boolean;
        /**
          * PROPS
         */
        "autocomplete": string;
        "autofocus": boolean;
        "autowidth": boolean;
        "disabled": boolean;
        "error": string;
        "getValidationMessage": () => Promise<string>;
        /**
          * METHODS
         */
        "getValidity": () => Promise<ValidityState>;
        "helptext": string;
        "inputid": string;
        "label": string;
        "labelup": boolean;
        "max": number;
        "min": number;
        "name": string;
        "nomargin": boolean;
        "required": boolean;
        "theme": 'inverse' | '';
        "value": Date | string;
    }
    interface FieldDatetime {
        "active": boolean;
        /**
          * PROPS
         */
        "autocomplete": string;
        "autofocus": boolean;
        "autowidth": boolean;
        "disabled": boolean;
        "error": string;
        "getValidationMessage": () => Promise<string>;
        /**
          * METHODS
         */
        "getValidity": () => Promise<ValidityState>;
        "helptext": string;
        "inputid": string;
        "label": string;
        "labelup": boolean;
        "max": number;
        "min": number;
        "name": string;
        "nomargin": boolean;
        "required": boolean;
        "showseconds": boolean;
        "theme": 'inverse' | '';
        "value": Date | string;
    }
    interface FieldFilter {
        /**
          * PROPS
         */
        "arrow": boolean;
        "autocomplete": string;
        "autowidth": boolean;
        "disabled": boolean;
        "error": string;
        "getValidationMessage": () => Promise<string>;
        /**
          * METHODS
         */
        "getValidity": () => Promise<ValidityState>;
        "helptext": string;
        "inputid": string;
        "label": string;
        "labelup": boolean;
        "name": string;
        "nomargin": boolean;
        "options": string | any[];
        "required": boolean;
        "theme": 'inverse' | '';
        "value": string;
    }
    interface FieldMultiselect {
        /**
          * PROPS
         */
        "autofocus": boolean;
        "autowidth": boolean;
        "disabled": boolean;
        "error": string;
        "getValidationMessage": () => Promise<string>;
        /**
          * METHODS
         */
        "getValidity": () => Promise<ValidityState>;
        "helptext": string;
        "inputid": string;
        "label": string;
        "name": string;
        "nomargin": boolean;
        "options": string | any[];
        "required": boolean;
        "theme": 'inverse' | '';
        "value": any[];
    }
    interface FieldNumber {
        /**
          * PROPS
         */
        "autocomplete": string;
        "autofocus": boolean;
        "autowidth": boolean;
        "disabled": boolean;
        "error": string;
        "getValidationMessage": () => Promise<string>;
        /**
          * METHODS
         */
        "getValidity": () => Promise<ValidityState>;
        "helptext": string;
        "inputid": string;
        "label": string;
        "labelup": boolean;
        "max": number;
        "min": number;
        "name": string;
        "nomargin": boolean;
        "required": boolean;
        "theme": 'inverse' | '';
        "value": number | undefined;
    }
    interface FieldRadio {
        /**
          * PROPS
         */
        "autowidth": boolean;
        "disabled": boolean;
        "error": string;
        "getValidationMessage": () => Promise<string>;
        /**
          * METHODS
         */
        "getValidity": () => Promise<ValidityState>;
        "helptext": string;
        "inputid": string;
        "label": string;
        "name": string;
        "nomargin": boolean;
        "options": string | any[];
        "required": boolean;
        "theme": 'inverse' | '';
        "value": string | undefined;
    }
    interface FieldRange {
        /**
          * PROPS
         */
        "autowidth": boolean;
        "disabled": boolean;
        "error": string;
        "getInternal": () => Promise<[number, number]>;
        "helptext": string;
        "inputid": string;
        "label": string;
        "maxvalue": number;
        "minvalue": number;
        "name": string;
        "nomargin": boolean;
        "required": boolean;
        "step": number;
        "theme": 'inverse' | '';
        "value": string;
        "valueinlabel": boolean;
    }
    interface FieldSelect {
        /**
          * PROPS
         */
        "autocomplete": string;
        "autowidth": boolean;
        "disabled": boolean;
        "error": string;
        "getValidationMessage": () => Promise<string>;
        /**
          * METHODS
         */
        "getValidity": () => Promise<ValidityState>;
        "helptext": string;
        "inputid": string;
        "label": string;
        "labelup": boolean;
        "name": string;
        "nomargin": boolean;
        "options": string | any[];
        "required": boolean;
        "theme": 'inverse' | '';
        "value": string;
    }
    interface FieldSlider {
        /**
          * PROPS
         */
        "autowidth": boolean;
        "disabled": boolean;
        "error": string;
        "helptext": string;
        "inputid": string;
        "label": string;
        "maxvalue": number;
        "minvalue": number;
        "name": string;
        "nomargin": boolean;
        "required": boolean;
        "step": number;
        "theme": 'inverse' | '';
        "value": number;
        "valueinlabel": boolean;
    }
    interface FieldText {
        /**
          * PROPS
         */
        "autocomplete": string;
        "autofocus": boolean;
        "autowidth": boolean;
        "count": number;
        "disabled": boolean;
        "error": string;
        "getValidationMessage": () => Promise<string>;
        /**
          * METHODS
         */
        "getValidity": () => Promise<ValidityState>;
        "helptext": string;
        "inputid": string;
        "label": string;
        "labelup": boolean;
        "maxlength": number;
        "minlength": number;
        "name": string;
        "nomargin": boolean;
        "required": boolean;
        "showcount": boolean;
        "theme": 'inverse' | '';
        "type": string;
        "value": string;
    }
    interface FieldTextarea {
        /**
          * PROPS
         */
        "autocomplete": string;
        "autofocus": boolean;
        "autowidth": boolean;
        "count": number;
        "disabled": boolean;
        "error": string;
        "fullwidth": boolean;
        "getValidationMessage": () => Promise<string>;
        /**
          * METHODS
         */
        "getValidity": () => Promise<ValidityState>;
        "helptext": string;
        "inputid": string;
        "label": string;
        "labelup": boolean;
        "maxlength": number;
        "minlength": number;
        "name": string;
        "nomargin": boolean;
        "required": boolean;
        "showcount": boolean;
        "theme": 'inverse' | '';
        "value": string;
    }
    interface FieldTime {
        /**
          * PROPS
         */
        "autowidth": boolean;
        "disabled": boolean;
        "error": string;
        "getInternal": () => Promise<InternalValue>;
        "getValidationMessage": () => Promise<string>;
        /**
          * METHODS
         */
        "getValidity": () => Promise<ValidityState>;
        "helptext": string;
        "inputid": string;
        "label": string;
        "labelup": boolean;
        "max": string;
        "min": string;
        "name": string;
        "nomargin": boolean;
        "required": boolean;
        "showseconds": boolean;
        "theme": 'inverse' | '';
        "value": string;
    }
    interface FunctionBuilder {
        /**
          * PROPS
         */
        "context": any;
        "value": string;
    }
    interface IconElement {
        "kind": string;
    }
    interface OverlayElement {
        /**
          * PROPS
         */
        "active": boolean;
    }
    interface RootElement {
        "theme": 'inverse' | '';
    }
    interface SaturationSlider {
        "color": () => ColorResult;
        "value": string;
    }
    interface SliderBar {
        "value": number;
        "vertical": boolean;
    }
    interface ToolTip {
        /**
          * PROPS
         */
        "active": boolean;
        "align": 'top' | 'bottom' | 'left' | 'right';
        "container": string | HTMLElement;
        "off": string;
        "on": string;
    }
}
declare global {
    interface HTMLAlphaSliderElement extends Components.AlphaSlider, HTMLStencilElement {
    }
    var HTMLAlphaSliderElement: {
        prototype: HTMLAlphaSliderElement;
        new (): HTMLAlphaSliderElement;
    };
    interface HTMLBackgroundFillElement extends Components.BackgroundFill, HTMLStencilElement {
    }
    var HTMLBackgroundFillElement: {
        prototype: HTMLBackgroundFillElement;
        new (): HTMLBackgroundFillElement;
    };
    interface HTMLCalendarDayElement extends Components.CalendarDay, HTMLStencilElement {
    }
    var HTMLCalendarDayElement: {
        prototype: HTMLCalendarDayElement;
        new (): HTMLCalendarDayElement;
    };
    interface HTMLCalendarHeaderElement extends Components.CalendarHeader, HTMLStencilElement {
    }
    var HTMLCalendarHeaderElement: {
        prototype: HTMLCalendarHeaderElement;
        new (): HTMLCalendarHeaderElement;
    };
    interface HTMLCalendarMonthElement extends Components.CalendarMonth, HTMLStencilElement {
    }
    var HTMLCalendarMonthElement: {
        prototype: HTMLCalendarMonthElement;
        new (): HTMLCalendarMonthElement;
    };
    interface HTMLColorInputsElement extends Components.ColorInputs, HTMLStencilElement {
    }
    var HTMLColorInputsElement: {
        prototype: HTMLColorInputsElement;
        new (): HTMLColorInputsElement;
    };
    interface HTMLColorPickerElement extends Components.ColorPicker, HTMLStencilElement {
    }
    var HTMLColorPickerElement: {
        prototype: HTMLColorPickerElement;
        new (): HTMLColorPickerElement;
    };
    interface HTMLColorWheelElement extends Components.ColorWheel, HTMLStencilElement {
    }
    var HTMLColorWheelElement: {
        prototype: HTMLColorWheelElement;
        new (): HTMLColorWheelElement;
    };
    interface HTMLDragXElement extends Components.DragX, HTMLStencilElement {
    }
    var HTMLDragXElement: {
        prototype: HTMLDragXElement;
        new (): HTMLDragXElement;
    };
    interface HTMLDragXyElement extends Components.DragXy, HTMLStencilElement {
    }
    var HTMLDragXyElement: {
        prototype: HTMLDragXyElement;
        new (): HTMLDragXyElement;
    };
    interface HTMLDragYElement extends Components.DragY, HTMLStencilElement {
    }
    var HTMLDragYElement: {
        prototype: HTMLDragYElement;
        new (): HTMLDragYElement;
    };
    interface HTMLDropDownElement extends Components.DropDown, HTMLStencilElement {
    }
    var HTMLDropDownElement: {
        prototype: HTMLDropDownElement;
        new (): HTMLDropDownElement;
    };
    interface HTMLElementTransitionElement extends Components.ElementTransition, HTMLStencilElement {
    }
    var HTMLElementTransitionElement: {
        prototype: HTMLElementTransitionElement;
        new (): HTMLElementTransitionElement;
    };
    interface HTMLEyeDropperElement extends Components.EyeDropper, HTMLStencilElement {
    }
    var HTMLEyeDropperElement: {
        prototype: HTMLEyeDropperElement;
        new (): HTMLEyeDropperElement;
    };
    interface HTMLFieldButtonElement extends Components.FieldButton, HTMLStencilElement {
    }
    var HTMLFieldButtonElement: {
        prototype: HTMLFieldButtonElement;
        new (): HTMLFieldButtonElement;
    };
    interface HTMLFieldCheckboxElement extends Components.FieldCheckbox, HTMLStencilElement {
    }
    var HTMLFieldCheckboxElement: {
        prototype: HTMLFieldCheckboxElement;
        new (): HTMLFieldCheckboxElement;
    };
    interface HTMLFieldColorElement extends Components.FieldColor, HTMLStencilElement {
    }
    var HTMLFieldColorElement: {
        prototype: HTMLFieldColorElement;
        new (): HTMLFieldColorElement;
    };
    interface HTMLFieldDateElement extends Components.FieldDate, HTMLStencilElement {
    }
    var HTMLFieldDateElement: {
        prototype: HTMLFieldDateElement;
        new (): HTMLFieldDateElement;
    };
    interface HTMLFieldDatetimeElement extends Components.FieldDatetime, HTMLStencilElement {
    }
    var HTMLFieldDatetimeElement: {
        prototype: HTMLFieldDatetimeElement;
        new (): HTMLFieldDatetimeElement;
    };
    interface HTMLFieldFilterElement extends Components.FieldFilter, HTMLStencilElement {
    }
    var HTMLFieldFilterElement: {
        prototype: HTMLFieldFilterElement;
        new (): HTMLFieldFilterElement;
    };
    interface HTMLFieldMultiselectElement extends Components.FieldMultiselect, HTMLStencilElement {
    }
    var HTMLFieldMultiselectElement: {
        prototype: HTMLFieldMultiselectElement;
        new (): HTMLFieldMultiselectElement;
    };
    interface HTMLFieldNumberElement extends Components.FieldNumber, HTMLStencilElement {
    }
    var HTMLFieldNumberElement: {
        prototype: HTMLFieldNumberElement;
        new (): HTMLFieldNumberElement;
    };
    interface HTMLFieldRadioElement extends Components.FieldRadio, HTMLStencilElement {
    }
    var HTMLFieldRadioElement: {
        prototype: HTMLFieldRadioElement;
        new (): HTMLFieldRadioElement;
    };
    interface HTMLFieldRangeElement extends Components.FieldRange, HTMLStencilElement {
    }
    var HTMLFieldRangeElement: {
        prototype: HTMLFieldRangeElement;
        new (): HTMLFieldRangeElement;
    };
    interface HTMLFieldSelectElement extends Components.FieldSelect, HTMLStencilElement {
    }
    var HTMLFieldSelectElement: {
        prototype: HTMLFieldSelectElement;
        new (): HTMLFieldSelectElement;
    };
    interface HTMLFieldSliderElement extends Components.FieldSlider, HTMLStencilElement {
    }
    var HTMLFieldSliderElement: {
        prototype: HTMLFieldSliderElement;
        new (): HTMLFieldSliderElement;
    };
    interface HTMLFieldTextElement extends Components.FieldText, HTMLStencilElement {
    }
    var HTMLFieldTextElement: {
        prototype: HTMLFieldTextElement;
        new (): HTMLFieldTextElement;
    };
    interface HTMLFieldTextareaElement extends Components.FieldTextarea, HTMLStencilElement {
    }
    var HTMLFieldTextareaElement: {
        prototype: HTMLFieldTextareaElement;
        new (): HTMLFieldTextareaElement;
    };
    interface HTMLFieldTimeElement extends Components.FieldTime, HTMLStencilElement {
    }
    var HTMLFieldTimeElement: {
        prototype: HTMLFieldTimeElement;
        new (): HTMLFieldTimeElement;
    };
    interface HTMLFunctionBuilderElement extends Components.FunctionBuilder, HTMLStencilElement {
    }
    var HTMLFunctionBuilderElement: {
        prototype: HTMLFunctionBuilderElement;
        new (): HTMLFunctionBuilderElement;
    };
    interface HTMLIconElementElement extends Components.IconElement, HTMLStencilElement {
    }
    var HTMLIconElementElement: {
        prototype: HTMLIconElementElement;
        new (): HTMLIconElementElement;
    };
    interface HTMLOverlayElementElement extends Components.OverlayElement, HTMLStencilElement {
    }
    var HTMLOverlayElementElement: {
        prototype: HTMLOverlayElementElement;
        new (): HTMLOverlayElementElement;
    };
    interface HTMLRootElementElement extends Components.RootElement, HTMLStencilElement {
    }
    var HTMLRootElementElement: {
        prototype: HTMLRootElementElement;
        new (): HTMLRootElementElement;
    };
    interface HTMLSaturationSliderElement extends Components.SaturationSlider, HTMLStencilElement {
    }
    var HTMLSaturationSliderElement: {
        prototype: HTMLSaturationSliderElement;
        new (): HTMLSaturationSliderElement;
    };
    interface HTMLSliderBarElement extends Components.SliderBar, HTMLStencilElement {
    }
    var HTMLSliderBarElement: {
        prototype: HTMLSliderBarElement;
        new (): HTMLSliderBarElement;
    };
    interface HTMLToolTipElement extends Components.ToolTip, HTMLStencilElement {
    }
    var HTMLToolTipElement: {
        prototype: HTMLToolTipElement;
        new (): HTMLToolTipElement;
    };
    interface HTMLElementTagNameMap {
        "alpha-slider": HTMLAlphaSliderElement;
        "background-fill": HTMLBackgroundFillElement;
        "calendar-day": HTMLCalendarDayElement;
        "calendar-header": HTMLCalendarHeaderElement;
        "calendar-month": HTMLCalendarMonthElement;
        "color-inputs": HTMLColorInputsElement;
        "color-picker": HTMLColorPickerElement;
        "color-wheel": HTMLColorWheelElement;
        "drag-x": HTMLDragXElement;
        "drag-xy": HTMLDragXyElement;
        "drag-y": HTMLDragYElement;
        "drop-down": HTMLDropDownElement;
        "element-transition": HTMLElementTransitionElement;
        "eye-dropper": HTMLEyeDropperElement;
        "field-button": HTMLFieldButtonElement;
        "field-checkbox": HTMLFieldCheckboxElement;
        "field-color": HTMLFieldColorElement;
        "field-date": HTMLFieldDateElement;
        "field-datetime": HTMLFieldDatetimeElement;
        "field-filter": HTMLFieldFilterElement;
        "field-multiselect": HTMLFieldMultiselectElement;
        "field-number": HTMLFieldNumberElement;
        "field-radio": HTMLFieldRadioElement;
        "field-range": HTMLFieldRangeElement;
        "field-select": HTMLFieldSelectElement;
        "field-slider": HTMLFieldSliderElement;
        "field-text": HTMLFieldTextElement;
        "field-textarea": HTMLFieldTextareaElement;
        "field-time": HTMLFieldTimeElement;
        "function-builder": HTMLFunctionBuilderElement;
        "icon-element": HTMLIconElementElement;
        "overlay-element": HTMLOverlayElementElement;
        "root-element": HTMLRootElementElement;
        "saturation-slider": HTMLSaturationSliderElement;
        "slider-bar": HTMLSliderBarElement;
        "tool-tip": HTMLToolTipElement;
    }
}
declare namespace LocalJSX {
    interface AlphaSlider {
        "color"?: () => ColorResult;
        "onAlphasliderinput"?: (event: CustomEvent<any>) => void;
        "value"?: string;
    }
    interface BackgroundFill {
        "color"?: string;
        "image"?: string;
        "line"?: string;
        "lineargradient"?: string;
        "onBackgroundchange"?: (event: CustomEvent<any>) => void;
        "positionx"?: string;
        "positiony"?: string;
        "radialgradient"?: string;
        "repeat"?: boolean | string;
        "sizex"?: string;
        "sizey"?: string;
    }
    interface CalendarDay {
        /**
          * PROPERTIES
         */
        "active"?: boolean;
        "clickable"?: boolean;
        "date"?: Date;
        "disabled"?: boolean;
        /**
          * EVENTS
         */
        "onDayclick"?: (event: CustomEvent<any>) => void;
    }
    interface CalendarHeader {
        /**
          * PROPS
         */
        "date"?: Date | string;
        "onDatechange"?: (event: CustomEvent<any>) => void;
    }
    interface CalendarMonth {
        /**
          * PROPERTIES
         */
        "active"?: boolean;
        "clickable"?: boolean;
        "date"?: string | Date;
        "disabled"?: boolean;
    }
    interface ColorInputs {
        "color"?: () => ColorResult;
        "onColorinputschanged"?: (event: CustomEvent<any>) => void;
        "onColorinputsmodechanged"?: (event: CustomEvent<any>) => void;
        "value"?: string;
    }
    interface ColorPicker {
        "color"?: () => ColorResult;
        "onColorpickerchanged"?: (event: CustomEvent<any>) => void;
        "value"?: string;
    }
    interface ColorWheel {
        "color"?: () => ColorResult;
        "onColorwheelchanged"?: (event: CustomEvent<any>) => void;
        "value"?: string;
    }
    interface DragX {
        "contained"?: boolean;
        "onMoved"?: (event: CustomEvent<any>) => void;
    }
    interface DragXy {
        "contained"?: boolean;
        "onMoved"?: (event: CustomEvent<any>) => void;
    }
    interface DragY {
        "contained"?: boolean;
        "onMoved"?: (event: CustomEvent<any>) => void;
    }
    interface DropDown {
        "arrow"?: boolean;
        "closeonclick"?: boolean;
        "onDropdownitemclicked"?: (event: CustomEvent<any>) => void;
        "open"?: boolean;
        "openonhover"?: boolean;
    }
    interface ElementTransition {
        "onElementtransitioned"?: (event: CustomEvent<any>) => void;
        "onElementtransitioning"?: (event: CustomEvent<any>) => void;
        "removeinactive"?: boolean;
        "speed"?: number;
    }
    interface EyeDropper {
        "onEyedropperpick"?: (event: CustomEvent<any>) => void;
    }
    interface FieldButton {
        "disabled"?: boolean;
        "kind"?: string;
        "nomargin"?: boolean;
        "size"?: string;
        "spinner"?: boolean;
        "theme"?: string;
        /**
          * PROPS
         */
        "type"?: string;
    }
    interface FieldCheckbox {
        /**
          * PROPS
         */
        "autofocus"?: boolean;
        "autowidth"?: boolean;
        "disabled"?: boolean;
        "error"?: string;
        "helptext"?: string;
        "inputid"?: string;
        "label"?: string;
        "mixed"?: boolean;
        "name"?: string;
        "nomargin"?: boolean;
        "novalidate"?: boolean;
        "onChanged"?: (event: CustomEvent<any>) => void;
        "required"?: boolean;
        "theme"?: 'inverse' | '';
        "value"?: boolean;
    }
    interface FieldColor {
        /**
          * PROPS
         */
        "autocomplete"?: string;
        "autofocus"?: boolean;
        "autowidth"?: boolean;
        "disabled"?: boolean;
        "error"?: string;
        "helptext"?: string;
        "inputid"?: string;
        "label"?: string;
        "labelup"?: boolean;
        "name"?: string;
        "nomargin"?: boolean;
        "onChanged"?: (event: CustomEvent<any>) => void;
        "required"?: boolean;
        "theme"?: 'inverse' | '';
        "value"?: string;
    }
    interface FieldDate {
        "active"?: boolean;
        /**
          * PROPS
         */
        "autocomplete"?: string;
        "autofocus"?: boolean;
        "autowidth"?: boolean;
        "disabled"?: boolean;
        "error"?: string;
        "helptext"?: string;
        "inputid"?: string;
        "label"?: string;
        "labelup"?: boolean;
        "max"?: number;
        "min"?: number;
        "name"?: string;
        "nomargin"?: boolean;
        "onChanged"?: (event: CustomEvent<any>) => void;
        "required"?: boolean;
        "theme"?: 'inverse' | '';
        "value"?: Date | string;
    }
    interface FieldDatetime {
        "active"?: boolean;
        /**
          * PROPS
         */
        "autocomplete"?: string;
        "autofocus"?: boolean;
        "autowidth"?: boolean;
        "disabled"?: boolean;
        "error"?: string;
        "helptext"?: string;
        "inputid"?: string;
        "label"?: string;
        "labelup"?: boolean;
        "max"?: number;
        "min"?: number;
        "name"?: string;
        "nomargin"?: boolean;
        "onChanged"?: (event: CustomEvent<any>) => void;
        "required"?: boolean;
        "showseconds"?: boolean;
        "theme"?: 'inverse' | '';
        "value"?: Date | string;
    }
    interface FieldFilter {
        /**
          * PROPS
         */
        "arrow"?: boolean;
        "autocomplete"?: string;
        "autowidth"?: boolean;
        "disabled"?: boolean;
        "error"?: string;
        "helptext"?: string;
        "inputid"?: string;
        "label"?: string;
        "labelup"?: boolean;
        "name"?: string;
        "nomargin"?: boolean;
        "onChanged"?: (event: CustomEvent<any>) => void;
        "options"?: string | any[];
        "required"?: boolean;
        "theme"?: 'inverse' | '';
        "value"?: string;
    }
    interface FieldMultiselect {
        /**
          * PROPS
         */
        "autofocus"?: boolean;
        "autowidth"?: boolean;
        "disabled"?: boolean;
        "error"?: string;
        "helptext"?: string;
        "inputid"?: string;
        "label"?: string;
        "name"?: string;
        "nomargin"?: boolean;
        "onChanged"?: (event: CustomEvent<any>) => void;
        "options"?: string | any[];
        "required"?: boolean;
        "theme"?: 'inverse' | '';
        "value"?: any[];
    }
    interface FieldNumber {
        /**
          * PROPS
         */
        "autocomplete"?: string;
        "autofocus"?: boolean;
        "autowidth"?: boolean;
        "disabled"?: boolean;
        "error"?: string;
        "helptext"?: string;
        "inputid"?: string;
        "label"?: string;
        "labelup"?: boolean;
        "max"?: number;
        "min"?: number;
        "name"?: string;
        "nomargin"?: boolean;
        "onChanged"?: (event: CustomEvent<any>) => void;
        "required"?: boolean;
        "theme"?: 'inverse' | '';
        "value"?: number | undefined;
    }
    interface FieldRadio {
        /**
          * PROPS
         */
        "autowidth"?: boolean;
        "disabled"?: boolean;
        "error"?: string;
        "helptext"?: string;
        "inputid"?: string;
        "label"?: string;
        "name"?: string;
        "nomargin"?: boolean;
        "onChanged"?: (event: CustomEvent<any>) => void;
        "options"?: string | any[];
        "required"?: boolean;
        "theme"?: 'inverse' | '';
        "value"?: string | undefined;
    }
    interface FieldRange {
        /**
          * PROPS
         */
        "autowidth"?: boolean;
        "disabled"?: boolean;
        "error"?: string;
        "helptext"?: string;
        "inputid"?: string;
        "label"?: string;
        "maxvalue"?: number;
        "minvalue"?: number;
        "name"?: string;
        "nomargin"?: boolean;
        "onChanged"?: (event: CustomEvent<any>) => void;
        "required"?: boolean;
        "step"?: number;
        "theme"?: 'inverse' | '';
        "value"?: string;
        "valueinlabel"?: boolean;
    }
    interface FieldSelect {
        /**
          * PROPS
         */
        "autocomplete"?: string;
        "autowidth"?: boolean;
        "disabled"?: boolean;
        "error"?: string;
        "helptext"?: string;
        "inputid"?: string;
        "label"?: string;
        "labelup"?: boolean;
        "name"?: string;
        "nomargin"?: boolean;
        "onChanged"?: (event: CustomEvent<any>) => void;
        "options"?: string | any[];
        "required"?: boolean;
        "theme"?: 'inverse' | '';
        "value"?: string;
    }
    interface FieldSlider {
        /**
          * PROPS
         */
        "autowidth"?: boolean;
        "disabled"?: boolean;
        "error"?: string;
        "helptext"?: string;
        "inputid"?: string;
        "label"?: string;
        "maxvalue"?: number;
        "minvalue"?: number;
        "name"?: string;
        "nomargin"?: boolean;
        "onChanged"?: (event: CustomEvent<any>) => void;
        "required"?: boolean;
        "step"?: number;
        "theme"?: 'inverse' | '';
        "value"?: number;
        "valueinlabel"?: boolean;
    }
    interface FieldText {
        /**
          * PROPS
         */
        "autocomplete"?: string;
        "autofocus"?: boolean;
        "autowidth"?: boolean;
        "count"?: number;
        "disabled"?: boolean;
        "error"?: string;
        "helptext"?: string;
        "inputid"?: string;
        "label"?: string;
        "labelup"?: boolean;
        "maxlength"?: number;
        "minlength"?: number;
        "name"?: string;
        "nomargin"?: boolean;
        "onChanged"?: (event: CustomEvent<any>) => void;
        "required"?: boolean;
        "showcount"?: boolean;
        "theme"?: 'inverse' | '';
        "type"?: string;
        "value"?: string;
    }
    interface FieldTextarea {
        /**
          * PROPS
         */
        "autocomplete"?: string;
        "autofocus"?: boolean;
        "autowidth"?: boolean;
        "count"?: number;
        "disabled"?: boolean;
        "error"?: string;
        "fullwidth"?: boolean;
        "helptext"?: string;
        "inputid"?: string;
        "label"?: string;
        "labelup"?: boolean;
        "maxlength"?: number;
        "minlength"?: number;
        "name"?: string;
        "nomargin"?: boolean;
        "onChanged"?: (event: CustomEvent<any>) => void;
        "required"?: boolean;
        "showcount"?: boolean;
        "theme"?: 'inverse' | '';
        "value"?: string;
    }
    interface FieldTime {
        /**
          * PROPS
         */
        "autowidth"?: boolean;
        "disabled"?: boolean;
        "error"?: string;
        "helptext"?: string;
        "inputid"?: string;
        "label"?: string;
        "labelup"?: boolean;
        "max"?: string;
        "min"?: string;
        "name"?: string;
        "nomargin"?: boolean;
        "onChanged"?: (event: CustomEvent<any>) => void;
        "onTimechange"?: (event: CustomEvent<any>) => void;
        /**
          * EVENTS
         */
        "onValuechange"?: (event: CustomEvent<any>) => void;
        "required"?: boolean;
        "showseconds"?: boolean;
        "theme"?: 'inverse' | '';
        "value"?: string;
    }
    interface FunctionBuilder {
        /**
          * PROPS
         */
        "context"?: any;
        "value"?: string;
    }
    interface IconElement {
        "kind"?: string;
    }
    interface OverlayElement {
        /**
          * PROPS
         */
        "active"?: boolean;
    }
    interface RootElement {
        "theme"?: 'inverse' | '';
    }
    interface SaturationSlider {
        "color"?: () => ColorResult;
        "onSaturationsliderinput"?: (event: CustomEvent<any>) => void;
        "value"?: string;
    }
    interface SliderBar {
        "onSliderbarinput"?: (event: CustomEvent<any>) => void;
        "value"?: number;
        "vertical"?: boolean;
    }
    interface ToolTip {
        /**
          * PROPS
         */
        "active"?: boolean;
        "align"?: 'top' | 'bottom' | 'left' | 'right';
        "container"?: string | HTMLElement;
        "off"?: string;
        "on"?: string;
    }
    interface IntrinsicElements {
        "alpha-slider": AlphaSlider;
        "background-fill": BackgroundFill;
        "calendar-day": CalendarDay;
        "calendar-header": CalendarHeader;
        "calendar-month": CalendarMonth;
        "color-inputs": ColorInputs;
        "color-picker": ColorPicker;
        "color-wheel": ColorWheel;
        "drag-x": DragX;
        "drag-xy": DragXy;
        "drag-y": DragY;
        "drop-down": DropDown;
        "element-transition": ElementTransition;
        "eye-dropper": EyeDropper;
        "field-button": FieldButton;
        "field-checkbox": FieldCheckbox;
        "field-color": FieldColor;
        "field-date": FieldDate;
        "field-datetime": FieldDatetime;
        "field-filter": FieldFilter;
        "field-multiselect": FieldMultiselect;
        "field-number": FieldNumber;
        "field-radio": FieldRadio;
        "field-range": FieldRange;
        "field-select": FieldSelect;
        "field-slider": FieldSlider;
        "field-text": FieldText;
        "field-textarea": FieldTextarea;
        "field-time": FieldTime;
        "function-builder": FunctionBuilder;
        "icon-element": IconElement;
        "overlay-element": OverlayElement;
        "root-element": RootElement;
        "saturation-slider": SaturationSlider;
        "slider-bar": SliderBar;
        "tool-tip": ToolTip;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "alpha-slider": LocalJSX.AlphaSlider & JSXBase.HTMLAttributes<HTMLAlphaSliderElement>;
            "background-fill": LocalJSX.BackgroundFill & JSXBase.HTMLAttributes<HTMLBackgroundFillElement>;
            "calendar-day": LocalJSX.CalendarDay & JSXBase.HTMLAttributes<HTMLCalendarDayElement>;
            "calendar-header": LocalJSX.CalendarHeader & JSXBase.HTMLAttributes<HTMLCalendarHeaderElement>;
            "calendar-month": LocalJSX.CalendarMonth & JSXBase.HTMLAttributes<HTMLCalendarMonthElement>;
            "color-inputs": LocalJSX.ColorInputs & JSXBase.HTMLAttributes<HTMLColorInputsElement>;
            "color-picker": LocalJSX.ColorPicker & JSXBase.HTMLAttributes<HTMLColorPickerElement>;
            "color-wheel": LocalJSX.ColorWheel & JSXBase.HTMLAttributes<HTMLColorWheelElement>;
            "drag-x": LocalJSX.DragX & JSXBase.HTMLAttributes<HTMLDragXElement>;
            "drag-xy": LocalJSX.DragXy & JSXBase.HTMLAttributes<HTMLDragXyElement>;
            "drag-y": LocalJSX.DragY & JSXBase.HTMLAttributes<HTMLDragYElement>;
            "drop-down": LocalJSX.DropDown & JSXBase.HTMLAttributes<HTMLDropDownElement>;
            "element-transition": LocalJSX.ElementTransition & JSXBase.HTMLAttributes<HTMLElementTransitionElement>;
            "eye-dropper": LocalJSX.EyeDropper & JSXBase.HTMLAttributes<HTMLEyeDropperElement>;
            "field-button": LocalJSX.FieldButton & JSXBase.HTMLAttributes<HTMLFieldButtonElement>;
            "field-checkbox": LocalJSX.FieldCheckbox & JSXBase.HTMLAttributes<HTMLFieldCheckboxElement>;
            "field-color": LocalJSX.FieldColor & JSXBase.HTMLAttributes<HTMLFieldColorElement>;
            "field-date": LocalJSX.FieldDate & JSXBase.HTMLAttributes<HTMLFieldDateElement>;
            "field-datetime": LocalJSX.FieldDatetime & JSXBase.HTMLAttributes<HTMLFieldDatetimeElement>;
            "field-filter": LocalJSX.FieldFilter & JSXBase.HTMLAttributes<HTMLFieldFilterElement>;
            "field-multiselect": LocalJSX.FieldMultiselect & JSXBase.HTMLAttributes<HTMLFieldMultiselectElement>;
            "field-number": LocalJSX.FieldNumber & JSXBase.HTMLAttributes<HTMLFieldNumberElement>;
            "field-radio": LocalJSX.FieldRadio & JSXBase.HTMLAttributes<HTMLFieldRadioElement>;
            "field-range": LocalJSX.FieldRange & JSXBase.HTMLAttributes<HTMLFieldRangeElement>;
            "field-select": LocalJSX.FieldSelect & JSXBase.HTMLAttributes<HTMLFieldSelectElement>;
            "field-slider": LocalJSX.FieldSlider & JSXBase.HTMLAttributes<HTMLFieldSliderElement>;
            "field-text": LocalJSX.FieldText & JSXBase.HTMLAttributes<HTMLFieldTextElement>;
            "field-textarea": LocalJSX.FieldTextarea & JSXBase.HTMLAttributes<HTMLFieldTextareaElement>;
            "field-time": LocalJSX.FieldTime & JSXBase.HTMLAttributes<HTMLFieldTimeElement>;
            "function-builder": LocalJSX.FunctionBuilder & JSXBase.HTMLAttributes<HTMLFunctionBuilderElement>;
            "icon-element": LocalJSX.IconElement & JSXBase.HTMLAttributes<HTMLIconElementElement>;
            "overlay-element": LocalJSX.OverlayElement & JSXBase.HTMLAttributes<HTMLOverlayElementElement>;
            "root-element": LocalJSX.RootElement & JSXBase.HTMLAttributes<HTMLRootElementElement>;
            "saturation-slider": LocalJSX.SaturationSlider & JSXBase.HTMLAttributes<HTMLSaturationSliderElement>;
            "slider-bar": LocalJSX.SliderBar & JSXBase.HTMLAttributes<HTMLSliderBarElement>;
            "tool-tip": LocalJSX.ToolTip & JSXBase.HTMLAttributes<HTMLToolTipElement>;
        }
    }
}
